apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    app: mariadb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mariadb
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-wd-pv
  labels:
    app: wp-wd
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: wp-wd
    fsType: ext4
