apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-be-pv
  labels:
    app: wp-be
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: wp-be
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    app: mariadb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mariadb
    fsType: ext4
