apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: core
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: mariadb
    tier: mysql-cache
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: core
  labels:
    app: mariadb
    tier: mysql-cache
spec:
  serviceName: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        tier: mysql-cache
    spec:
      containers:
      - image: mariadb:10
        name: mariadb
        env:
          # $ kubectl create secret generic mysql-pass-root --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-root
              key: password.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-persistent-storage
      labels:
        app: mariadb
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          app: mariadb
