apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: core
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis      
  selector:
    app: redis
    tier: mysql-cache
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: core
  labels:
    app: redis
    tier: mysql-cache
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
        tier: mysql-cache
    spec:
      containers:
      - image: redis:3
        name: redis
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: redis-pass.txt
        ports:
        - containerPort: 6379
          name: redis
          args: ["--requirepass $REDIS_PASS"]
