apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wp-fpm
    tier: frontend
    track: stable
  name: wp-fpm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-fpm
      name: wp-nginx
      tier: frontend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp-fpm
        name: wp-nginx
        tier: frontend
        track: stable
    spec:
      containers:
#      - env:
#        - name: WORDPRESS_DB_HOST
#          value: mariadb.core.svc.cluster.local
#        - name: WORDPRESS_DB_NAME
#          value: dbWPWD
#        - name: WORDPRESS_DB_USER
#          value: wp-fpm
#        - name: WORDPRESS_DB_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              key: mariadb-pass-wp-fpm.txt
#              name: mariadb-pass-wp-fpm
      - image: daxio/wordpress-redis-sock:v1.1.0
        imagePullPolicy: IfNotPresent
        name: wp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: wp-fpm-pv-claim
        - mountPath: /usr/local/etc/php/conf.d
          name: php
        - mountPath: /var/run/nginx-cache
          name: cache
        - mountPath: /sock
          name: php-socket
# Mis configs
        - mountPath: /var/www/html/wp-config.php
          name: wp-fpm-config         
          subPath: wp-config.php
#          readOnly: true
      - image: daxio/nginx-naxsi:v1.2
        imagePullPolicy: IfNotPresent
        name: wp-nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: wp-fpm-pv-claim
        - mountPath: /etc/nginx
          name: nginx
        - mountPath: /etc/nginx-conf/conf.d
          name: nginx-conf-d
        - mountPath: /etc/nginx-conf/global
          name: nginx-global
        - mountPath: /etc/nginx-conf/html
          name: nginx-html
        - mountPath: /var/run/nginx-cache
          name: cache
        - mountPath: /sock
          name: php-socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 33
      terminationGracePeriodSeconds: 30
      volumes:
      - name: wp-fpm-pv-claim
        persistentVolumeClaim:
          claimName: wp-fpm-pv-claim
      - configMap:
          defaultMode: 420
          name: php
        name: php
      - configMap:
          defaultMode: 420
          name: nginx
        name: nginx
      - configMap:
          defaultMode: 420
          name: nginx-conf-d
        name: nginx-conf-d
      - configMap:
          defaultMode: 420
          name: nginx-global
        name: nginx-global
      - configMap:
          defaultMode: 420
          name: nginx-html
        name: nginx-html
# Mis configs
      - configMap:
          defaultMode: 420
          name: wp-fpm-config
        name: wp-fpm-config
      - emptyDir:
          medium: Memory
        name: cache
      - emptyDir: {}
        name: php-socket
status: {}
