apiVersion: v1
kind: Service
metadata:
  name: wp-fpm
  namespace: default
  labels:
    app: wp-fpm
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: wp-fpm
    tier: frontend
  type: ClusterIP
