apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-wd-pv
  labels:
    app: wp-wd
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sc-r3-cms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
