apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-wd-pv-claim
  namespace: wp-wd
  labels:
    app: wp-wd
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sc-r3-cms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: wp-wd
