apiVersion: v1
kind: Service
metadata:
  name: wp-wd
  namespace: wp-wd
  labels:
    app: wp-wd
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: wp-wd
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-wd-pv-claim
  namespace: wp-wd
  labels:
    app: wp-wd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: wp-wd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-wd
  namespace: wp-wd
  labels:
    app: wp-wd
    tier: frontend
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: wp-nginx
        app: wp-wd
        tier: frontend
    spec:
      containers:
      - image: chepurko/wordpress-fpm-redis:v1.0
        name: wp-fpm
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.core.svc.cluster.local # this must be the FQDN of the mariadb Service
        - name: WORDPRESS_DB_NAME
          value: dbWPWD
        - name: WORDPRESS_DB_USER
          value: wp-wd
        - name: WORDPRESS_DB_PASSWORD
          value: ENTER_A_PASSWORD
          #valueFrom:
          #  secretKeyRef:
          #    name: mariadb-pass-wp-wd
          #    key: mariadb-pass-wp-wd.txt
        #optional since nginx can see WP on localhost
        #ports:
        #- containerPort: 9000
        #  name: php
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      - image: chepurko/nginx-fpm
        name: nginx-fpm
        env:
        - name: BEHIND_PROXY
          value: "true"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-wd-pv-claim
