apiVersion: v1
kind: Service
metadata:
  name: wp-wd
  namespace: wp-wd
  labels:
    app: wp-wd
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: wp-wd
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-wd-pv-claim
  namespace: wp-wd
  labels:
    app: wp-wd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: slow
  selector:
    matchLabels:
      app: wp-wd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-wd
  namespace: wp-wd
  labels:
    app: wp-wd
    tier: frontend
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: wp-apache
        app: wp-wd
        tier: frontend
    spec:
      containers:
      - image: chepurko/wordpress-redis:v1.3-fpm
        name: wp
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.core.svc.cluster.local # this must be the FQDN of the mariadb Service
        - name: WORDPRESS_DB_NAME
          value: dbWPWD
        - name: WORDPRESS_DB_USER
          value: wp-wd
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass-wp-wd
              key: mariadb-pass-wp-wd.txt
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: php
          mountPath: /usr/local/etc/php/conf.d
      - image: chepurko/nginx-sec-cache:v1.13
        name: wp-nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: nginx
          mountPath: /etc/nginx
        - name: nginx-conf-d
          mountPath: /etc/nginx/conf.d
        - name: nginx-global
          mountPath: /etc/nginx/global
        - name: nginx-html
          mountPath: /etc/nginx/html
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-wd-pv-claim
      - name: php
        configMap:
          name: php
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-conf-d
        configMap:
          name: nginx-conf-d
      - name: nginx-global
        configMap:
          name: nginx-global
      - name: nginx-html
        configMap:
          name: nginx-html
