apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-wd
  namespace: wp-wd
  labels:
    app: wp-wd
    tier: frontend
    track: stable
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: wp-nginx
        app: wp-wd
        tier: frontend
        track: stable
    spec:
      containers:
      - image: daxio/wordpress-redis:v1.5-fpm
        name: wp
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.core.svc.cluster.local # this must be the FQDN of the mariadb Service
        - name: WORDPRESS_DB_NAME
          value: dbWPWD
        - name: WORDPRESS_DB_USER
          value: wp-wd
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass-wp-wd
              key: mariadb-pass-wp-wd.txt
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: php
          mountPath: /usr/local/etc/php/conf.d
        - name: cache
          mountPath: /var/run/nginx-cache
      - image: daxio/nginx-naxsi:v1.1.2
        name: wp-nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: nginx
          mountPath: /etc/nginx
        - name: nginx-conf-d
          mountPath: /etc/nginx-conf/conf.d
        - name: nginx-global
          mountPath: /etc/nginx-conf/global
        - name: nginx-html
          mountPath: /etc/nginx-conf/html
        - name: cache
          mountPath: /var/run/nginx-cache
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-wd-pv-claim
      - name: php
        configMap:
          name: php
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-conf-d
        configMap:
          name: nginx-conf-d
      - name: nginx-global
        configMap:
          name: nginx-global
      - name: nginx-html
        configMap:
          name: nginx-html
      - name: cache
        emptyDir:
          medium: "Memory"
