apiVersion: v1
data:
  wp-cache.conf: "server {\n  server_name _;\n\n  root /var/www/html;\n  include /etc/nginx-conf/global/*.conf;\n\n
    \ set $skip_cache 0;\n  set $naxsi_flag_enable \"\";\n\n  # POST requests and
    urls with a query string should always go to PHP\n  if ($request_method = POST)
    {\n    set $skip_cache 1;\n  }   \n\n  if ($query_string != \"\") {\n    set $skip_cache
    1;\n  }   \n\n  # Don't cache uris containing the following segments\n  if ($request_uri
    ~* \"/wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml\")
    {\n    set $skip_cache 1;\n  }   \n\n  # Don't use the cache for logged in users
    or recent commenters\n  if ($http_cookie ~* \"comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in\")
    {\n    set $skip_cache 1;\n  }\n\n  if ($arg_customize_changeset_uuid != \"\")
    {\n    set $naxsi_flag_enable 0;\n  }\n\n  location / {\n    try_files $uri $uri/
    /index.php?$args;\n    include /etc/nginx-conf/global/*.rules;\n  }    \n\n  location
    ~ \\.php$ {\n    try_files $uri =404; \n    include fastcgi_params;\n    limit_req
    zone=one burst=12 nodelay;\n    fastcgi_pass php;\n\n    fastcgi_cache_bypass
    $skip_cache;\n    fastcgi_no_cache $skip_cache;\n\n    fastcgi_cache WORDPRESS;\n
    \   fastcgi_cache_valid  60m;\n  }\n}\n"
  wp.conf.OFF: |
    server {
            ## Your website name goes here.
            server_name _;
            ## Your only path reference.
            ## This should be in your http block and if it is, it's not needed here.
            #index index.php;

            root /var/www/html;
            include /etc/nginx-conf/global/*.conf;

            set $naxsi_flag_enable "";

            if ($arg_customize_changeset_uuid != "") {
                    set $naxsi_flag_enable 0;
            }

            location / {
                    # This is cool because no php is touched for static content.
                    # include the "?$args" part so non-default permalinks doesn't break when using query string
                    try_files $uri $uri/ /index.php?$args;
                    include /etc/nginx-conf/global/*.rules;
            }

            location ~ \.php$ {
                    #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
                    limit_req zone=one burst=12 nodelay;
                    include fastcgi_params;
                    fastcgi_pass php;
            }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-09T00:00:50Z"
  name: nginx-conf-d
  namespace: wp-wd
  resourceVersion: "2987"
  selfLink: /api/v1/namespaces/wp-wd/configmaps/nginx-conf-d
  uid: 5ec65dd5-dc87-4d97-8e1b-87f6ce4b3191
